[package]
name = "sugar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
if_chain = "1.0.2"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1.18.0"